version: '3'
services:
  # my-ui:
  #   container_name: my-ui
  #   build: ./my-ui
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - my-api
  #   networks:
  #     - test-network

  # my-api:
  #   container_name: my-api
  #   restart: always
  #   build:
  #     context: my-api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   #command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
  #   depends_on:
  #     - rabbitmq
  #     - mp-redis
  #   networks:
  #     - test-network
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - test-network

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    command: mongod
    networks:
      - test-network

volumes:
  mongo-data:
networks:
  test-network: