version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - test-network

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    command: mongod
    networks:
      - test-network

volumes:
  mongo-data:
networks:
  test-network:
